services:
  web:
    build: .
    container_name: pdfsalarie_app
    ports:
      - "8000:8000"
    volumes:
      # Map the local assets folder to the container to persist files and logs
      - ./assets:/app/assets
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_TO=charlessabenin@gmail.com
      - SMTP_USER=herve.koffi@cperformers.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    restart: unless-stopped
